require("plugins.core")
require("plugins.filetree")
require("plugins.treesitter")
require("plugins.formatter")
require("plugins.completion")
require("plugins.linter")
require("plugins.fuzzy")
require("plugins.cursor")
